### ISSUE TITLE
Dev Requirements

### ISSUE THREAD

**Issue by pkumaschow** [dwagon/Hostinfo#34]
Doco should mention that python-dev is a required package for development... or I'm blind...

gcc failed without it when running

pip install -r requirements-dev.txt

Also needed package libyaml-dev

**Comment by dwagon** [comment]
It isn't required for hostinfo itself, but for some of the modules that
hostinfo uses.
I'll add it to the docs though.

On Thu, Mar 10, 2016 at 11:00 AM, Peter Kumaschow <notifications@github.com>
wrote:

> Doco should mention that python-dev is a required package... or I'm
> blind...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dwagon/Hostinfo/issues/34>.
>



-- 
Dougal Scott

No matter how long you teach a fool, he still knows everything.
   -- Leonid S. Sukhorukov

**Comment by dwagon** [comment]
Merged in
